"""Buyer-focused copy, keeping the restrained CH3F visual identity."""
COPY = {
 'it': {
  'hero1':'Macchine kebab.', 'hero2':'Coltelli elettrici.', 'heroEyebrow':'Attrezzature per la ristorazione',
  'intro':'Elettrico o gas. Lame da 80 o 120 mm. La selezione TOROS per il tuo locale, con una richiesta su misura.',
  'homeTitle':'Macchine kebab e coltelli elettrici | CH3F', 'machineTitle':'Macchine kebab professionali: elettriche e a gas', 'knifeTitle':'Coltelli kebab elettrici: 80 e 120 mm',
  'compareMachine':'Elettrico o gas? Parti dal tuo locale.', 'compareKnife':'80 o 120 mm? Confronta le lame.',
  'compareIntro':'Confronta i dati di catalogo, poi completa la scelta con le esigenze della tua cucina.',
  'checkBefore':'Da verificare per il tuo locale',
  'electricCheck':'Tensione, fasi e potenza disponibili; peso dello spiedo previsto.', 'gasCheck':'Tipo e pressione del gas; posizione del motore e peso dello spiedo previsto.',
  'knifeCheck':'Peso, impugnatura, alimentazione, pulizia e ricambi. Il diametro da solo non determina la produttività.',
  'optionalDetails':'Aggiungi dettagli del locale (facoltativo)', 'quoteTitle':'Il tuo prossimo passo.',
  'quoteIntro':'Scegli l’attrezzatura, indica email e paese di consegna. Puoi aggiungere i dettagli del locale quando li hai.',
  'ctaText':'Macchina, coltello o entrambi: parti dall’attrezzatura che ti serve e prepara la tua richiesta.',
  'previewShort':'Anteprima: riepilogo scaricabile, invio non ancora attivo.',
  'chatLabel':'Parliamone su WhatsApp', 'chatIntro':'Hai una domanda sulla scelta? Scrivici su WhatsApp.',
  'whatsappDraft':'Ciao CH3F, vorrei informazioni su: {product}.',
  'whatsappUnavailable':'Il contatto WhatsApp CH3F sarà disponibile a breve. Per ora puoi preparare una richiesta.',
  'chatClose':'Chiudi', 'chatContinue':'Apri WhatsApp', 'chatNotice':'Si apre WhatsApp. Il messaggio viene inviato solo quando scegli di inviarlo.',
 },
 'de': {
  'hero1':'Dönergrills.', 'hero2':'Elektrische Dönermesser.', 'heroEyebrow':'Ausstattung für die Gastronomie',
  'intro':'Elektro oder Gas. Klingen mit 80 oder 120 mm. Die TOROS-Auswahl für deinen Betrieb – passend zu deiner Anfrage.',
  'homeTitle':'Dönergrills & elektrische Dönermesser | CH3F', 'machineTitle':'Dönergrills für die Gastronomie: Elektro & Gas', 'knifeTitle':'Elektrische Dönermesser: 80 und 120 mm',
  'compareMachine':'Elektro oder Gas? Dein Betrieb entscheidet.', 'compareKnife':'80 oder 120 mm? Klingen im Vergleich.',
  'compareIntro':'Vergleiche die Katalogangaben und ergänze die Anforderungen deiner Küche.', 'checkBefore':'Für deinen Betrieb zu klären',
  'electricCheck':'Verfügbare Spannung, Phasen und Anschlussleistung; geplantes Spießgewicht.', 'gasCheck':'Gasart und Gasdruck; Motorposition und geplantes Spießgewicht.',
  'knifeCheck':'Gewicht, Griff, Stromversorgung, Reinigung und Ersatzteile. Der Durchmesser allein bestimmt nicht die Schneidleistung.',
  'optionalDetails':'Betriebsdetails ergänzen (optional)', 'quoteTitle':'Dein nächster Schritt.',
  'quoteIntro':'Wähle die Ausstattung und gib E-Mail und Lieferland an. Betriebsdetails kannst du ergänzen, sobald sie feststehen.',
  'ctaText':'Grill, Messer oder beides: Wähle die benötigte Ausstattung und bereite deine Anfrage vor.',
  'previewShort':'Vorschau: Zusammenfassung zum Download, Versand noch nicht aktiv.',
  'chatLabel':'Schreib uns auf WhatsApp', 'chatIntro':'Fragen zur Auswahl? Schreib uns auf WhatsApp.',
  'whatsappDraft':'Hallo CH3F, ich interessiere mich für: {product}.',
  'whatsappUnavailable':'Der CH3F-WhatsApp-Kontakt ist bald verfügbar. Bis dahin kannst du eine Anfrage vorbereiten.',
  'chatClose':'Schließen', 'chatContinue':'WhatsApp öffnen', 'chatNotice':'WhatsApp wird geöffnet. Du entscheidest dort, ob du die Nachricht sendest.',
 },
 'en': {
  'hero1':'Kebab machines.', 'hero2':'Electric knives.', 'heroEyebrow':'Equipment for professional kitchens',
  'intro':'Electric or gas. Blades of 80 or 120 mm. Explore the TOROS selection for your kitchen and prepare a tailored enquiry.',
  'homeTitle':'Kebab machines & electric kebab knives | CH3F', 'machineTitle':'Professional kebab machines: electric & gas', 'knifeTitle':'Electric kebab knives: 80 and 120 mm',
  'compareMachine':'Electric or gas? Start with your kitchen.', 'compareKnife':'80 or 120 mm? Compare the blades.',
  'compareIntro':'Compare the catalogue specifications, then add your kitchen’s requirements.', 'checkBefore':'Check for your kitchen',
  'electricCheck':'Available voltage, phases and electrical capacity; intended spit weight.', 'gasCheck':'Gas type and pressure; motor position and intended spit weight.',
  'knifeCheck':'Weight, grip, power supply, cleaning and spare parts. Diameter alone does not determine throughput.',
  'optionalDetails':'Add business details (optional)', 'quoteTitle':'Your next step.',
  'quoteIntro':'Choose your equipment, email and delivery country. Add business details when you have them.',
  'ctaText':'A machine, a knife or both: start with the equipment you need and prepare your enquiry.',
  'previewShort':'Preview: downloadable summary; sending is not active yet.',
  'chatLabel':'Talk to us on WhatsApp', 'chatIntro':'A question about your choice? Talk to us on WhatsApp.',
  'whatsappDraft':'Hello CH3F, I would like information about: {product}.',
  'whatsappUnavailable':'The CH3F WhatsApp contact will be available soon. You can prepare an enquiry in the meantime.',
  'chatClose':'Close', 'chatContinue':'Open WhatsApp', 'chatNotice':'Opens WhatsApp. The message is only sent when you choose to send it there.',
 },
 'fr': {
  'hero1':'Machines à kebab.', 'hero2':'Couteaux électriques.', 'heroEyebrow':'Équipement pour la restauration',
  'intro':'Électrique ou gaz. Lames de 80 ou 120 mm. Découvrez la sélection TOROS pour votre établissement et préparez votre demande.',
  'homeTitle':'Machines à kebab & couteaux électriques | CH3F', 'machineTitle':'Machines à kebab professionnelles : électriques et à gaz', 'knifeTitle':'Couteaux à kebab électriques : 80 et 120 mm',
  'compareMachine':'Électrique ou gaz ? Partez de votre cuisine.', 'compareKnife':'80 ou 120 mm ? Comparez les lames.',
  'compareIntro':'Comparez les caractéristiques du catalogue, puis précisez les besoins de votre cuisine.', 'checkBefore':'À vérifier pour votre établissement',
  'electricCheck':'Tension, phases et puissance disponibles ; poids prévu de la broche.', 'gasCheck':'Type et pression du gaz ; position du moteur et poids prévu de la broche.',
  'knifeCheck':'Poids, prise en main, alimentation, nettoyage et pièces détachées. Le diamètre seul ne détermine pas le rendement.',
  'optionalDetails':'Ajouter les détails de l’établissement (facultatif)', 'quoteTitle':'Votre prochaine étape.',
  'quoteIntro':'Choisissez votre équipement, indiquez votre e-mail et le pays de livraison. Ajoutez les détails de votre établissement dès que vous les avez.',
  'ctaText':'Une machine, un couteau ou les deux : choisissez l’équipement souhaité et préparez votre demande.',
  'previewShort':'Aperçu : récapitulatif téléchargeable ; envoi pas encore actif.',
  'chatLabel':'Échangeons sur WhatsApp', 'chatIntro':'Une question sur votre choix ? Écrivez-nous sur WhatsApp.',
  'whatsappDraft':'Bonjour CH3F, je souhaite des informations sur : {product}.',
  'whatsappUnavailable':'Le contact WhatsApp CH3F sera bientôt disponible. Vous pouvez préparer une demande en attendant.',
  'chatClose':'Fermer', 'chatContinue':'Ouvrir WhatsApp', 'chatNotice':'Ouvre WhatsApp. Vous choisissez ensuite d’envoyer le message.',
 },
 'es': {
  'hero1':'Máquinas de kebab.', 'hero2':'Cuchillos eléctricos.', 'heroEyebrow':'Equipamiento para hostelería',
  'intro':'Electricidad o gas. Hojas de 80 o 120 mm. Descubre la selección TOROS para tu local y prepara tu consulta.',
  'homeTitle':'Máquinas de kebab y cuchillos eléctricos | CH3F', 'machineTitle':'Máquinas de kebab profesionales: eléctricas y de gas', 'knifeTitle':'Cuchillos de kebab eléctricos: 80 y 120 mm',
  'compareMachine':'¿Electricidad o gas? Empieza por tu cocina.', 'compareKnife':'¿80 o 120 mm? Compara las hojas.',
  'compareIntro':'Compara los datos del catálogo y añade las necesidades de tu cocina.', 'checkBefore':'Qué comprobar para tu local',
  'electricCheck':'Tensión, fases y potencia disponibles; peso previsto del asador.', 'gasCheck':'Tipo y presión del gas; posición del motor y peso previsto del asador.',
  'knifeCheck':'Peso, agarre, alimentación, limpieza y recambios. El diámetro por sí solo no determina la productividad.',
  'optionalDetails':'Añadir datos del negocio (opcional)', 'quoteTitle':'Tu siguiente paso.',
  'quoteIntro':'Elige el equipo e indica tu email y el país de entrega. Añade los datos del local cuando los tengas.',
  'ctaText':'Una máquina, un cuchillo o ambos: elige el equipo que necesitas y prepara tu consulta.',
  'previewShort':'Vista previa: resumen descargable; el envío aún no está activo.',
  'chatLabel':'Hablemos por WhatsApp', 'chatIntro':'¿Tienes dudas sobre qué elegir? Escríbenos por WhatsApp.',
  'whatsappDraft':'Hola CH3F, me gustaría recibir información sobre: {product}.',
  'whatsappUnavailable':'El contacto de WhatsApp de CH3F estará disponible pronto. Mientras tanto, puedes preparar una consulta.',
  'chatClose':'Cerrar', 'chatContinue':'Abrir WhatsApp', 'chatNotice':'Abre WhatsApp. El mensaje solo se envía cuando tú lo decides.',
 },
 'pt': {
  'hero1':'Máquinas de kebab.', 'hero2':'Facas elétricas.', 'heroEyebrow':'Equipamento para restauração',
  'intro':'Eletricidade ou gás. Lâminas de 80 ou 120 mm. Descubra a seleção TOROS para o seu espaço e prepare o seu pedido.',
  'homeTitle':'Máquinas de kebab e facas elétricas | CH3F', 'machineTitle':'Máquinas de kebab profissionais: elétricas e a gás', 'knifeTitle':'Facas de kebab elétricas: 80 e 120 mm',
  'compareMachine':'Eletricidade ou gás? Comece pela sua cozinha.', 'compareKnife':'80 ou 120 mm? Compare as lâminas.',
  'compareIntro':'Compare os dados do catálogo e acrescente os requisitos da sua cozinha.', 'checkBefore':'O que verificar para o seu espaço',
  'electricCheck':'Tensão, fases e potência disponíveis; peso previsto do espeto.', 'gasCheck':'Tipo e pressão do gás; posição do motor e peso previsto do espeto.',
  'knifeCheck':'Peso, pega, alimentação, limpeza e peças de substituição. O diâmetro por si só não determina a produtividade.',
  'optionalDetails':'Adicionar detalhes do negócio (opcional)', 'quoteTitle':'O seu próximo passo.',
  'quoteIntro':'Escolha o equipamento e indique o email e o país de entrega. Acrescente os detalhes do espaço quando os tiver.',
  'ctaText':'Uma máquina, uma faca ou ambas: escolha o equipamento de que precisa e prepare o seu pedido.',
  'previewShort':'Pré-visualização: resumo para descarregar; envio ainda não ativo.',
  'chatLabel':'Fale connosco no WhatsApp', 'chatIntro':'Tem dúvidas sobre a escolha? Escreva-nos no WhatsApp.',
  'whatsappDraft':'Olá CH3F, gostaria de receber informações sobre: {product}.',
  'whatsappUnavailable':'O contacto WhatsApp da CH3F estará disponível em breve. Entretanto, pode preparar um pedido.',
  'chatClose':'Fechar', 'chatContinue':'Abrir WhatsApp', 'chatNotice':'Abre o WhatsApp. A mensagem só é enviada quando decidir enviá-la.',
 },
 'tr': {
  'hero1':'Döner makineleri.', 'hero2':'Elektrikli bıçaklar.', 'heroEyebrow':'Profesyonel mutfak ekipmanları',
  'intro':'Elektrik veya gaz. 80 ya da 120 mm bıçaklar. İşletmeniz için TOROS seçkisini inceleyin, ihtiyacınıza göre talep hazırlayın.',
  'homeTitle':'Döner makineleri ve elektrikli döner bıçakları | CH3F', 'machineTitle':'Profesyonel döner makineleri: elektrikli ve gazlı', 'knifeTitle':'Elektrikli döner bıçakları: 80 ve 120 mm',
  'compareMachine':'Elektrik mi gaz mı? Mutfağınızdan başlayın.', 'compareKnife':'80 mi 120 mm mi? Bıçakları karşılaştırın.',
  'compareIntro':'Katalog bilgilerini karşılaştırın ve mutfağınızın ihtiyaçlarını ekleyin.', 'checkBefore':'İşletmeniz için kontrol edin',
  'electricCheck':'Mevcut voltaj, faz sayısı ve elektrik gücü; planlanan şiş ağırlığı.', 'gasCheck':'Gaz türü ve basıncı; motor konumu ve planlanan şiş ağırlığı.',
  'knifeCheck':'Ağırlık, tutuş, enerji kaynağı, temizlik ve yedek parçalar. Çap tek başına verimliliği belirlemez.',
  'optionalDetails':'İşletme bilgilerini ekleyin (isteğe bağlı)', 'quoteTitle':'Sıradaki adımınız.',
  'quoteIntro':'Ekipmanı seçin, e-posta adresinizi ve teslimat ülkesini belirtin. İşletme bilgilerini hazır olduğunda ekleyebilirsiniz.',
  'ctaText':'Makine, bıçak veya her ikisi: ihtiyacınız olan ekipmanı seçin ve talebinizi hazırlayın.',
  'previewShort':'Önizleme: indirilebilir özet; gönderim henüz etkin değil.',
  'chatLabel':'WhatsApp üzerinden konuşalım', 'chatIntro':'Seçiminizle ilgili sorunuz mu var? WhatsApp üzerinden yazın.',
  'whatsappDraft':'Merhaba CH3F, şu ürün hakkında bilgi almak istiyorum: {product}.',
  'whatsappUnavailable':'CH3F WhatsApp iletişimi yakında kullanıma açılacak. Şimdilik bir talep hazırlayabilirsiniz.',
  'chatClose':'Kapat', 'chatContinue':'WhatsApp’ı aç', 'chatNotice':'WhatsApp açılır. Mesajı yalnızca siz göndermeyi seçtiğinizde gönderir.',
 }
}
