GUIDE_DEPTH={
 'it':[
  ['Confrontare i costi di utilizzo','Per stimare un costo energetico serve un consumo riferito a condizioni di lavoro comparabili. Per l’elettrico, energia consumata in kWh × tariffa per kWh dà il costo dell’energia. Per il gas, usa l’unità di consumo e la tariffa corrispondenti. La potenza nominale in kW non è una misura del consumo effettivo durante un intero servizio.','Chiedi al fornitore come è stato misurato il consumo: carico, durata e impostazioni. Un confronto privo di queste condizioni può far apparire più conveniente una macchina senza descrivere il lavoro nel tuo locale.'],
  ['Valutare il coltello come attrezzatura completa','Confronta 80 e 120 mm insieme al peso completo del coltello, all’impugnatura, alla regolazione di taglio e alla dotazione. Se hai già una postazione, indica il modello utilizzato e quali accessori vorresti mantenere.','Richiedi l’elenco di alimentatore, cavi, lame e accessori inclusi. Chiedi inoltre i codici delle lame compatibili e le istruzioni del produttore per pulizia e manutenzione: la sola corrispondenza del diametro non prova che un ricambio sia adatto.'],
  ['Rendere confrontabili due preventivi','Confronta offerte riferite allo stesso modello e alla stessa dotazione. Oltre al prezzo dell’attrezzatura, separa imposte, trasporto, eventuale installazione e accessori. Annota i tempi di consegna confermati e le condizioni di pagamento.','Per l’assistenza, chiedi chi interviene, dove e con quali condizioni. Garanzia, ricambi e manutenzione devono essere descritti nell’offerta, senza presumere che siano inclusi. Queste informazioni aiutano a confrontare il costo della fornitura e l’organizzazione del servizio.']
 ],
 'de':[
  ['Betriebskosten nachvollziehbar vergleichen','Eine Energieschätzung benötigt Verbrauchswerte unter vergleichbaren Arbeitsbedingungen. Beim Elektrogerät ergibt verbrauchte Energie in kWh × Tarif je kWh die Energiekosten. Beim Gasgerät müssen Verbrauchseinheit und Tarif zusammenpassen. Die Nennleistung in kW beschreibt nicht den tatsächlichen Energieverbrauch während eines gesamten Arbeitstags.','Frage nach den Messbedingungen: Beladung, Dauer und Einstellungen. Ohne diese Angaben kann ein Gerät günstiger erscheinen, ohne die Abläufe deines Betriebs abzubilden.'],
  ['Das Messer als vollständige Ausstattung bewerten','Vergleiche 80 und 120 mm zusammen mit vollständigem Gewicht, Griff, Schnitteinstellung und Lieferumfang. Nenne bei einer bestehenden Station das bisherige Modell und die Zubehörteile, die du weiterverwenden möchtest.','Fordere eine Auflistung von Netzteil, Kabeln, Klingen und weiterem enthaltenem Zubehör an. Frage außerdem nach kompatiblen Klingennummern und den Herstelleranweisungen für Reinigung und Wartung. Der gleiche Durchmesser allein belegt nicht, dass ein Ersatzteil passt.'],
  ['Zwei Angebote vergleichbar machen','Vergleiche Angebote für dasselbe Modell und denselben Lieferumfang. Trenne Gerätepreis, Steuern, Transport, eine mögliche Installation und Zubehör. Halte bestätigte Lieferzeiten und Zahlungsbedingungen fest.','Kläre beim Service, wer unter welchen Bedingungen vor Ort oder anderweitig hilft. Garantie, Ersatzteile und Wartung sollten ausdrücklich beschrieben sein. So lassen sich Lieferkosten und die Organisation des späteren Betriebs besser beurteilen.']
 ]}
