# Revised editorial direction: Italian industrial design, restrained language.
REFINED={
'it':{'hero1':'La cucina professionale.','hero2':'Una nuova prospettiva.','intro':'Macchine döner kebab e coltelli elettrici. Una selezione in cui funzione, dettagli e cura della presentazione trovano il loro spazio.','rangeTitle':'Due gesti essenziali.\nCuocere. Tagliare.','rangeIntro':'Attrezzature da scegliere con attenzione. Per una cucina che riflette il tuo modo di lavorare.','ctaTitle':'Ogni cucina\nha il suo progetto.','ctaText':'Troviamo insieme la configurazione per il tuo locale.','footerLine':'Una nuova prospettiva sulla cucina professionale.'},
'de':{'hero1':'Professionelle Küche.','hero2':'Neu betrachtet.','intro':'Dönergrills und elektrische Dönermesser. Eine Auswahl, die Funktion, Details und eine klare Gestaltung zusammenbringt.','rangeTitle':'Zwei wesentliche Schritte.\nGrillen. Schneiden.','rangeIntro':'Ausstattung, bewusst gewählt. Für eine Küche, die deine Arbeitsweise widerspiegelt.','ctaTitle':'Jede Küche\nbeginnt mit einer Idee.','ctaText':'Finden wir gemeinsam die passende Konfiguration für deinen Betrieb.','footerLine':'Eine neue Perspektive auf professionelle Küchen.'},
'en':{'hero1':'Professional kitchens.','hero2':'A fresh perspective.','intro':'Döner kebab machines and electric knives. A considered selection where function, detail and presentation come together.','rangeTitle':'Two essential gestures.\nCook. Carve.','rangeIntro':'Equipment, thoughtfully chosen. For a kitchen that reflects the way you work.','ctaTitle':'Every kitchen\nbegins with an idea.','ctaText':'Let’s find the configuration for your space.','footerLine':'A fresh perspective on professional kitchens.'},
'fr':{'hero1':'La cuisine professionnelle.','hero2':'Une nouvelle perspective.','intro':'Machines à döner kebab et couteaux électriques. Une sélection qui associe fonction, détails et soin de la présentation.','rangeTitle':'Deux gestes essentiels.\nCuire. Découper.','rangeIntro':'Des équipements choisis avec soin. Pour une cuisine qui reflète votre façon de travailler.','ctaTitle':'Chaque cuisine\na son projet.','ctaText':'Trouvons ensemble la configuration adaptée à votre établissement.','footerLine':'Un nouveau regard sur la cuisine professionnelle.'},
'es':{'hero1':'La cocina profesional.','hero2':'Una nueva perspectiva.','intro':'Máquinas de döner kebab y cuchillos eléctricos. Una selección que reúne función, detalles y cuidado por la presentación.','rangeTitle':'Dos gestos esenciales.\nCocinar. Cortar.','rangeIntro':'Equipos elegidos con criterio. Para una cocina que refleje tu forma de trabajar.','ctaTitle':'Cada cocina\ntiene su proyecto.','ctaText':'Encontremos la configuración adecuada para tu local.','footerLine':'Una nueva perspectiva de la cocina profesional.'},
'pt':{'hero1':'A cozinha profissional.','hero2':'Uma nova perspetiva.','intro':'Máquinas de döner kebab e facas elétricas. Uma seleção que alia função, detalhes e cuidado na apresentação.','rangeTitle':'Dois gestos essenciais.\nCozinhar. Cortar.','rangeIntro':'Equipamentos escolhidos com cuidado. Para uma cozinha que reflete a sua forma de trabalhar.','ctaTitle':'Cada cozinha\ntem o seu projeto.','ctaText':'Vamos encontrar a configuração adequada ao seu estabelecimento.','footerLine':'Uma nova perspetiva sobre a cozinha profissional.'},
'tr':{'hero1':'Profesyonel mutfaklar.','hero2':'Yeni bir bakış açısı.','intro':'Döner makineleri ve elektrikli bıçaklar. İşlevi, detayları ve özenli sunumu bir araya getiren bir seçki.','rangeTitle':'İki temel adım.\nPişirmek. Kesmek.','rangeIntro':'Özenle seçilen ekipmanlar. Çalışma biçiminizi yansıtan bir mutfak için.','ctaTitle':'Her mutfak\nbir fikirle başlar.','ctaText':'İşletmeniz için uygun yapılandırmayı birlikte bulalım.','footerLine':'Profesyonel mutfaklara yeni bir bakış açısı.'}}
